version: 1

integrations:
  - name: Jira
    base: 'https://confluence.company.com'
    templates:
      - name: Spaces
        alias: 'cf/{{ space }}'
        link: 'https://confluence.company.com/display/{{ space }}'
